### ISSUE TITLE
'identifier' is only available on OS X 10.13 or newer

### ISSUE THREAD

**Issue by thunpisit** [scottjg/switchmate#2]
There is error on these 2 line 62 and 131 saying 'identifier' is only available on OS X 10.13 or newer

```
let uuid = peripheral.identifier.uuidString

fputs("Connected to Switchmate \(peripheral.identifier.uuidString), discovering services...\n", stderr)
```

**Comment by thevickypedia** [comment]
@thunpisit did you ever try to find a solution for this?

**Comment by thunpisit** [comment]
@thevickypedia Tbh I gave up on Switchmate a long time along since Bluetooth is not reliable. I would recommend going with IoT devices either IFTTT that works with Google or something more of a hardware DIY solution like particle.io
